export { Navbar } from './Navbar';
export { Hero } from './Hero';
export { StatsBar } from './StatsBar';
export { HowItWorks } from './HowItWorks';
export { WhyNida } from './WhyNida';
export { NomosProtocol } from './NomosProtocol';
export { FAQ } from './FAQ';
export { FinalCTA } from './FinalCTA';
export { Footer } from './Footer';
